# Products schema

# --- !Ups

CREATE SEQUENCE COMPANY_ID_SEQ;

CREATE TABLE COMPANY (
    ID INTEGER NOT NULL DEFAULT nextval('COMPANY_ID_SEQ'),
    NAME VARCHAR(64)
);

CREATE SEQUENCE PRODUCT_ID_SEQ;

CREATE TABLE PRODUCT (
    ID INTEGER NOT NULL DEFAULT nextval('PRODUCT_ID_SEQ'),
    NAME VARCHAR(64),
    COLOUR VARCHAR(24),
    SIZE VARCHAR(12),
    COMPANY_ID INTEGER
);

# --- !Downs

DROP TABLE COMPANY;
DROP SEQUENCE COMPANY_ID_SEQ;

DROP TABLE PRODUCT;
DROP SEQUENCE PRODUCT_ID_SEQ;
